=== saff17/zna-.jaz./značkovací jazyky/XML, XSD, XSL/XSD.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="seznamapps">
    <xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="komunikacniapp"></xs:element>
			</xs:sequence>
		</xs:complexType>
</xs:element>

<xs:element name="komunikacniapp">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="ID" type="xs:integer"/>
            <xs:element name="nazev" type="xs:string"/>
            <xs:element ref="vydavatel"/>           
            <xs:element name="pocet_zamestnancu" type="xs:integer"/>     
            <xs:element ref="vyuziti_v_CR"/>  
            <xs:element ref="vyuziti_v_zahranici"/> 
            <xs:element ref="komercni_vyuziti"/>
            <xs:element ref="bezne_vyuziti"/> 
        </xs:sequence>
            <xs:attribute name="udrzovany" type="xs:boolean"/>
            <xs:attribute name="vchodu" type="xs:boolean"/>                
    </xs:complexType>
</xs:element>

<xs:element name="vydavatel">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="developer" type="xs:string"/>
            <xs:element name="rok_vzniku" type="xs:date"/>
            <xs:element ref="CEO"/>
        </xs:sequence>
            <xs:attribute name="networth" use="optional" type="xs:string"  />
    </xs:complexType>
</xs:element>

<xs:element name="CEO">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="firstname"/>
            <xs:element name="surname"/>
        </xs:sequence>  
            <xs:attribute name="pohlavi" use="optional" type="gender"  />                          
    </xs:complexType>
</xs:element>

<xs:element name="vyuziti_v_CR">
    <xs:complexType>
        <xs:sequence>
          <xs:group ref="vyuziti"/>
        </xs:sequence>
        <xs:attribute name="pomer_vyuziti" use="required" type="xs:string"/>           
    </xs:complexType>
  </xs:element>

  <xs:element name="vyuziti_v_zahranici">
    <xs:complexType>
        <xs:sequence>
          <xs:group ref="vyuziti"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="komercni_vyuziti">
    <xs:complexType>
        <xs:sequence>
          <xs:group ref="vyuziti"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="bezne_vyuziti">
    <xs:complexType>
        <xs:sequence>
          <xs:group ref="vyuziti"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>

<xs:group name="vyuziti">
        <xs:sequence>
            <xs:element name="rating" type="hodnoty"/>
        </xs:sequence>
</xs:group>

<xs:simpleType name="hodnoty">
    <xs:restriction base="xs:string">
        <xs:enumeration value="malé" />
        <xs:enumeration value="střední" />
        <xs:enumeration value="velké" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="gender">
    <xs:restriction base="xs:string">
        <xs:enumeration value="muž"/>
        <xs:enumeration value="žena"/>
        <xs:enumeration value="ještěr"/>
        <xs:enumeration value="jiné"/>       
    </xs:restriction>
</xs:simpleType>


</xs:schema>

=== saff17/zna-.jaz./značkovací jazyky/XML, XSD, XSL/XML.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="XSL.xsl" ?>

<seznamapps  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD.xsd"> 

<komunikacniapp udrzovany="true" vchodu="true">
    <ID>1</ID>
    <nazev>Facebook</nazev>
    <vydavatel networth="500mld$">
        <developer>Meta Platforms</developer>
        <rok_vzniku>2004-04-02</rok_vzniku>
            <CEO pohlavi="ještěr">
                <firstname>Mark</firstname>
                <surname>Zuckerberg</surname>
            </CEO>
    </vydavatel>
    <pocet_zamestnancu>35587</pocet_zamestnancu>

    <vyuziti_v_CR pomer_vyuziti="50%">
        <rating>malé</rating>
    </vyuziti_v_CR>   

    <vyuziti_v_zahranici>
        <rating>velké</rating>
    </vyuziti_v_zahranici>  

    <komercni_vyuziti>
        <rating>střední</rating>
    </komercni_vyuziti>

    <bezne_vyuziti>
        <rating>velké</rating>
    </bezne_vyuziti>

</komunikacniapp>

    <komunikacniapp udrzovany="true" vchodu="true">
        <ID>999</ID>
        <nazev>Instagram</nazev>
        <vydavatel networth="500mld$">
            <developer>Meta Platforms</developer>
            <rok_vzniku>2010-06-10</rok_vzniku>
                <CEO pohlavi="ještěr">
                    <firstname>Mark</firstname>
                    <surname>Zuckerberg</surname>
                </CEO>
        </vydavatel>
        <pocet_zamestnancu>35587</pocet_zamestnancu>
    
        <vyuziti_v_CR pomer_vyuziti="30%">
            <rating>střední</rating>
        </vyuziti_v_CR>   
    
        <vyuziti_v_zahranici>
            <rating>velké</rating>
        </vyuziti_v_zahranici>  
    
        <komercni_vyuziti>
            <rating>velké</rating>
        </komercni_vyuziti>
    
        <bezne_vyuziti>
            <rating>velké</rating>
        </bezne_vyuziti>
</komunikacniapp>

<komunikacniapp udrzovany="true" vchodu="true">
    <ID>5</ID>
    <nazev>Discord</nazev>
    <vydavatel networth="500mld$">
        <developer>Discord Inc.</developer>
        <rok_vzniku>2015-06-03</rok_vzniku>
            <CEO pohlavi="muž">
                <firstname>Jason</firstname>
                <surname>Citron</surname>
            </CEO>
    </vydavatel>
    <pocet_zamestnancu>750</pocet_zamestnancu>

    <vyuziti_v_CR pomer_vyuziti="nezname">
        <rating>malé</rating>
    </vyuziti_v_CR>   

    <vyuziti_v_zahranici>
        <rating>střední</rating>
    </vyuziti_v_zahranici>  

    <komercni_vyuziti>
        <rating>malé</rating>
    </komercni_vyuziti>

    <bezne_vyuziti>
        <rating>velké</rating>
    </bezne_vyuziti>
</komunikacniapp>

<komunikacniapp udrzovany="true" vchodu="true">
    <ID>20</ID>
    <nazev>Skype</nazev>
    <vydavatel networth="1trilion$">
        <developer>Microsoft</developer>
        <rok_vzniku>2003-10-26</rok_vzniku>
            <CEO pohlavi="muž">
                <firstname>Satya</firstname>
                <surname>Nadella</surname>
            </CEO>
    </vydavatel>
    <pocet_zamestnancu>182000</pocet_zamestnancu>

    <vyuziti_v_CR pomer_vyuziti="nezname">
        <rating>malé</rating>
    </vyuziti_v_CR>   

    <vyuziti_v_zahranici>
        <rating>malé</rating>
    </vyuziti_v_zahranici>  

    <komercni_vyuziti>
        <rating>malé</rating>
    </komercni_vyuziti>

    <bezne_vyuziti>
        <rating>malé</rating>
    </bezne_vyuziti>  
</komunikacniapp>


<komunikacniapp udrzovany="false" vchodu="false">
    <ID>60</ID>
    <nazev>Friendster</nazev>
    <vydavatel networth="0$">
        <developer>Mol global</developer>
        <rok_vzniku>2002-01-01</rok_vzniku>
            <CEO pohlavi="muž">
                <firstname>Ganesh</firstname>
                <surname>Bangah</surname>
            </CEO>
    </vydavatel>
    <pocet_zamestnancu>0</pocet_zamestnancu>

    <vyuziti_v_CR pomer_vyuziti="nezname">
        <rating>malé</rating>
    </vyuziti_v_CR>   

    <vyuziti_v_zahranici>
        <rating>malé</rating>
    </vyuziti_v_zahranici>  

    <komercni_vyuziti>
        <rating>malé</rating>
    </komercni_vyuziti>

    <bezne_vyuziti>
        <rating>malé</rating>
    </bezne_vyuziti>
</komunikacniapp>


<komunikacniapp udrzovany="false" vchodu="true">
    <ID>69</ID>
    <nazev>Teamspeak</nazev>
    <vydavatel networth="1100$">
        <developer>TeamSpeak Systems GmbH</developer>
        <rok_vzniku>2001-08-01</rok_vzniku>
            <CEO pohlavi="muž">
                <firstname>Ralf</firstname>
                <surname>Ludwig</surname>
            </CEO>
    </vydavatel>
    <pocet_zamestnancu>6</pocet_zamestnancu>

    <vyuziti_v_CR pomer_vyuziti="nezname">
        <rating>velké</rating>
    </vyuziti_v_CR>   

    <vyuziti_v_zahranici>
        <rating>střední</rating>
    </vyuziti_v_zahranici>  

    <komercni_vyuziti>
        <rating>malé</rating>
    </komercni_vyuziti>

    <bezne_vyuziti>
        <rating>velké</rating>
    </bezne_vyuziti>
</komunikacniapp>

<komunikacniapp udrzovany="true" vchodu="true">
    <ID>420</ID>
    <nazev>Twitter</nazev>
    <vydavatel networth="200mill$">
        <developer>TeamSpeak Systems GmbH</developer>
        <rok_vzniku>2006-03-26</rok_vzniku>
            <CEO pohlavi="muž">
                <firstname>Jack</firstname>
                <surname>Dorsey</surname>
            </CEO>
    </vydavatel>
    <pocet_zamestnancu>4900</pocet_zamestnancu>

    <vyuziti_v_CR pomer_vyuziti="nezname">
        <rating>malé</rating>
    </vyuziti_v_CR>   

    <vyuziti_v_zahranici>
        <rating>velké</rating>
    </vyuziti_v_zahranici>  

    <komercni_vyuziti>
        <rating>malé</rating>
    </komercni_vyuziti>

    <bezne_vyuziti>
        <rating>malé</rating>
    </bezne_vyuziti>
</komunikacniapp>

<komunikacniapp udrzovany="false" vchodu="false">
    <ID>640</ID>
    <nazev>ICQ</nazev>
    <vydavatel networth="0$">
        <developer>Mirabilis</developer>
        <rok_vzniku>1996-05-04</rok_vzniku>
            <CEO pohlavi="muž">
                <firstname>Yair </firstname>
                <surname>Goldfinger</surname>
            </CEO>
    </vydavatel>
    <pocet_zamestnancu>0</pocet_zamestnancu>

    <vyuziti_v_CR pomer_vyuziti="nezname">
        <rating>velké</rating>
    </vyuziti_v_CR>   

    <vyuziti_v_zahranici>
        <rating>malé</rating>
    </vyuziti_v_zahranici>  

    <komercni_vyuziti>
        <rating>malé</rating>
    </komercni_vyuziti>

    <bezne_vyuziti>
        <rating>střední</rating>
    </bezne_vyuziti>
</komunikacniapp>


<komunikacniapp udrzovany="true" vchodu="true">
    <ID>19</ID>
    <nazev>Microsoft teams</nazev>
    <vydavatel networth="1trilion$">
        <developer>Microsoft</developer>
        <rok_vzniku>2003-10-26</rok_vzniku>
            <CEO pohlavi="muž">
                <firstname>Satya</firstname>
                <surname>Nadella</surname>
            </CEO>
    </vydavatel>
    <pocet_zamestnancu>182000</pocet_zamestnancu>

    <vyuziti_v_CR pomer_vyuziti="nezname">
        <rating>střední</rating>
    </vyuziti_v_CR>   

    <vyuziti_v_zahranici>
        <rating>střední</rating>
    </vyuziti_v_zahranici>  

    <komercni_vyuziti>
        <rating>velké</rating>
    </komercni_vyuziti>

    <bezne_vyuziti>
        <rating>malé</rating>
    </bezne_vyuziti>
</komunikacniapp>

<komunikacniapp udrzovany="true" vchodu="true">
    <ID>700</ID>
    <nazev>ZOOM</nazev>
    <vydavatel networth="12mil$">
        <developer>Zoom Video Communications</developer>
        <rok_vzniku>2011-05-21</rok_vzniku>
            <CEO pohlavi="muž">
                <firstname>Eric </firstname>
                <surname>Yuan</surname>
            </CEO>
    </vydavatel>
    <pocet_zamestnancu>0</pocet_zamestnancu>

    <vyuziti_v_CR pomer_vyuziti="nezname">
        <rating>střední</rating>
    </vyuziti_v_CR>   

    <vyuziti_v_zahranici>
        <rating>velké</rating>
    </vyuziti_v_zahranici>  

    <komercni_vyuziti>
        <rating>velké</rating>
    </komercni_vyuziti>

    <bezne_vyuziti>
        <rating>malé</rating>
    </bezne_vyuziti>
</komunikacniapp>


</seznamapps>
